[project]
name = "ifaman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julius", email = "julius.platzer@icloud.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ifaman = "ifaman:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
